const TUL_KEYS_ORDER = [
  "sajujirugi",
  "sajumakgi",
  "chonji",
  "dangun",
  "dosan",
  "wonhyo",
  "yulgok",
  "joonggun",
  "toigye",
  "hwarang",
  "choongmoo",
  "kwangae",
  "poeum",
  "gebaek",
  "euiam",
  "choongjang",
  "juche",
  "choiyong",
  "samil",
  "yoosin",
];

const tules = {
  sajujirugi: {
    name: "Saju Jirugi",
    gup: "Gup 10",
    video: "weiDnCTeflM",
    description: "Cruz de Ataque.",
    belt: "Blanco",
    diagram: "Cruz",
    qtyMovements: 7,
    junbi: "Narani Junbi Sogi",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [
      "Desplazar el pie derecho a D formando una posicion para caminar realizando un golpe a altura media con el puño derecho",
      "Desplazar el pie derecho a A (Mirando a B) Formando una posicion para caminar realizando un bloqueo bajo con el antebrazo izquierdo",
      "Desplazar el pie derecho a B formando una posicion para caminar realizando un golpe a altura media con el puño derecho",
      "Desplazar el pi derecho a D (Mirando a C) formando una posicion para caminar realizando un bloqueo bajo con el antebrazo izquierdo",
      "Desplazar el pie derecho a C formando una posicion para caminar realizando un golpe a altura media con el puño derecho",
      "Desplazar el pie derecho a B (Mirando a A) formando una posicion para caminar realizando un bloqueo bajo con el antebrazo izquierdo",
      "Desplazar el pie derecho a A realizando un golpe a altura media con el puño derecho",
      "Desplazar el pie derecho a la posicion preparatoria",
    ],
    times: [
      "0m03.057s",
      "0m04.802s",
      "0m06.700s",
      "0m08.440s",
      "0m10.056s",
      "0m12.090s",
      "0m13.731s",
      "0m16.170s",
    ],
  },
  sajumakgi: {
    name: "Saju Makgi",
    gup: "Gup 10",
    video: "v9j4dN6Kzeo",
    description: "Cruz de defensa.",
    belt: "Blanco",
    diagram: "Cruz",
    qtyMovements: 8,
    junbi: "Narani Junbi Sogi",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [
      "Desplazar el pie derecho a C (Mirando a D) formando una posicion para caminar realizando un bloqueo bajo con canto de mano izquierda",
      "Desplazar el pie derecho a D formando una posicion para caminar realizando un bloqueo a altura media con la parte interna del antebrazo derecho",
      "Desplazar el pie derecho a A (Mirando a B) formando una posicion para caminar realizando unbloqueo bajo con canto de mano izquierda",
      "Desplazar el pie derecho a B formando una posicion para caminar realizando un bloqueo a altura media con la parte interna del antebrazo derecho",
      "Desplazar el pie derecho a D (mirando a C) formando una posicion para caminar realizando un bloqueo bajo con canto de mano izquierda",
      "Desplazar el pie derecho a C formando una posicion para caminar realizando un bloqueo a altura media con la parte interna del antebrazo derecho",
      "Desplazar el pie derecho a B (Mirando a A) formando una posicion para caminar realizando un bloqueo bajo con canto de mano izquierda",
      "Desplazar el pie derecho a A formando una posicion para caminar realizando un bloqueo a altura media con la parte interna del antebrazo derecho",
      "Desplazar el pie derecho a la posicion preparatoria",
    ],
    times: [
      "0m03.003s",
      "0m04.884s",
      "0m06.724s",
      "0m08.397s",
      "0m10.207s",
      "0m12.114s",
      "0m13.886s",
      "0m15.815s",
      "0m18.816s",
    ],
  },
  chonji: {
    name: "Chon-ji",
    gup: "Gup 9",
    video: "4vAdfbs0Rlo",
    description:
      "Aignifica literalmente 'El Cielo - La Tierra'. Esto es interpretado en  Oriente como la creación del mundo o el principio de la historia de la Humanidad, por tal motivo este tul es ejecutado por el principiante. Consiste en dos partes similares: una representa el Cielo y la otra, la Tierra.",
    belt: "Blanco punta Amarilla",
    diagram: "Cruz",
    qtyMovements: 19,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [
      "Desplazar el pie izquierdo hacia B formando una posición para caminar con un bloqueo bajo con antebrazo izquierdo",
      "Desplazar el pie derecho a B realizando un golpe de puño con la derecha al pecho",
      "Desplazar el pie derecho a A girando en sentido de las agujas del reloj (por el lado del puño o espalda) llegando a una posicion para caminar con una defensa baja con antabrazo derecho",
      "Desplazar el pie izquierdo a A logrando una posicion para caminar con un golpe de puño izquierdo al pecho",
      "Desplazar el pie izquierdo a D realizando una defensa baja con canto de mano izquierdo",
      "Desplazar el pie derecho a D formando una posicion para caminar con un puño al pecho con la derecha",
      "Desplazar el pie derecho a C girando en sentido delas agujas del reloj (por el lado del puño o espalda) para formar una posicion para caminar con un bloqueo bajo con antebrezo derecho",
      "Desplazar el pie izquierdo a C formando una posicion para caminar con un puño al pecho con la izquierda",
      "Desplazar el pie izquierdo a A formando una posicion 'L' haciendo una defenza con canto de mano a zona media con el antebrazo izquierdo",
      "Desplazar el pie derechoa a A formando una posicion para caminar con un puño al pecho con la derecha",
      "Desplazar el pie derecho a B girando en sentido de las agujas del reloj (por el lado del puño o espalda) formando una posicion en 'L' haciendo un defensa a altura media con atebrazo derecho",
      "Desplazar el pie izquierdo a B formando una posicion para caminar con un puño al pecho con la izquierda",
      "Dezplazar el pie izquierdo a C girando en sentido de las agujas del reloj (por el lado del puño o espalda) formando una posicion en 'L' haciendo una defensa a altura media con antebrazo izquierdo",
      "Dezplazar el pie derecho a C formandi una posicion para caminar con un puño al pecho con la derecha",
      "Desplazar el pie derecho a D girando en sentido de las agujas del reloj (por el lado del puño o espalda) formando una posicion en 'L' haciendo una defensa a altura media con antebrazo derecho",
      "Desplazar el pie izquierdo a D formando una posicion para caminar con un puño al pecho con la izquierda",
      "Desplazar el pie derecho a D formando una posicion para caminar con un puño al pecho con la derecha",
      "Desplazar el pie derecho a C (dar un paso hacia atras) formando una posicion para caminar con un puño al pecho con la izquierda",
      "Desplazar el pie izquierdo a C (dar un paso hacia atras) formando una posicion para caminar con un golpe de puño al pecho con la derecha",
    ],
    times: [
      "0m01.984s",
      "0m03.526s",
      "0m05.317s",
      "0m06.867s",
      "0m08.508s",
      "0m10.075s",
      "0m11.943s",
      "0m13.433s",
      "0m14.951s",
      "0m16.669s",
      "0m18.220s",
      "0m19.839s",
      "0m21.709s",
      "0m23.320s",
      "0m25.030",
      "0m26.622s",
      "0m28.204s",
      "0m29.861s",
      "0m31.465s",
    ],
  },
  dangun: {
    name: "Dan Gun",
    gup: "Gup 8",
    video: "4W9lza3V5R4",
    description:
      "Es el nombre del Santo Legendario fundador de Corea en el 2333 A.C. (Antes de Cristo)",
    belt: "Amarillo",
    diagram: "Doble T",
    qtyMovements: 21,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [
		"Desplazar el pie izquierdo a B, formando una posicion L a B, realizando una defensa a altura media a B con canto de mano izqierda",
		"Desplazar el pie derecho a B, formando una posicion de caminar a B, dando un golpe alto (Al filtrum, espacio entre la nariz y la boca) con el puño derecho a B",
		"Girando en sentido horario, mover el pie derecho a A, formando una posicion L a A, realizando una defensa a altura media con canto de mano derecha",
		"Desplazar el pie izquierdo a A, formando una posicion de caminar, dando un golpe alto con el puño izquierdo a A", 
		"Desplazar el pie izquierdo a D, formando una posicion de caminar, realizando una defensa a altura baja con el antebrazo izquierdo a D",
		"Desplazar el pie derecho a D, formando una posicion de caminar, dando un golpe alto con el puño derecho a D",
		"Desplazar el pie izquierdo a D, formando una posicion de caminar, dando un golpe alto con el puño izquierdo a D",
		"Desplazar el pie derecho a D, formando una posicion de caminar, dando un golpe de puño alto con el puño derecho a D",
		"Girando en sentido antihorario desplazar el pie izquierdo a E, formando una posicion L realizando un bloqueo con los dos antebrazos a E",
		"Desplazar el pie derecho a E, formando una posicion para caminar, dando un golpe alto con el puño derecho a E",
		"Girando en sentido horario desplazar el pie derecho a F, formando una posicion L, realizando un bloqueo doble con ambos antebrazos",
		"Desplazar el pie izquierdo a F, formando una posicion de caminar, dando un golpe alto con el puño izquierdo",
		"Desplazar el pie izquierdo a C, formando una posicion de caminar, realizando una defensa a altura baja con el antebrazo izquierdo (Realizar movimiento 13 y 14 de forma continua)",
		"Manteniendo la posicion de caminar, realizar una defensa alta con el antebrazo izquierdo (Realizar movimiento 13 y 14 de forma continua)",
		"Desplazar el pie derecho a C, formando una posicion de caminar, realizando una defensa alta con el antebrazo derecho",
		"Desplazar el pie izquierdo a c, formando una posicion de caminar, realizando un bloqueo alto con el antebrazo izquierdo",
		"Desplazar el pie derecho a C, formando una posicion de caminar, realizando una defensa alta con el antebrazo derecho",
		"Girando en sentido antihorario, desplazar el pie izquierdo a B, formando una posicion L, dando un golpe a altura media a B con canto de mano izquierda",
		"Desplazar el pie derecho a B, formando una posicion de caminar, dando un golpe alto a B con el puño derecho",
		"Girando en sentido horario, dezplazar el pie derechoa a A, formando una posicion L, dando un golpe a altura media a A con canto de mano derecha",
		"Desplazar el pie izquierdo a A, formando una posicion de caminar, dando un golpe alto a A con el puño izquierdo",
		"Traer el pie izquierdo para volver a la posicion inicial"
	],
    times: ["0m02.847s",
			"0m04.504s",
			"0m06.223s",
			"0m07.807s",
			"0m09.461s",
			"0m11.074s",
			"0m12.609s",
			"0m14.153s",
			"0m15.868s",
			"0m17.518s",
			"0m19.195s",
			"0m20.819s",
			"0m22.444s",
			"0m24.101s",
			"0m25.743s",
			"0m27.447s",
			"0m29.071s",
			"0m30.624s",
			"0m32.372s",
			"0m34.031s",
			"0m35.744s",
			"0m40.129s"],
  },
  dosan: {
    name: "Do San",
    gup: "Gup 7",
    video: "ofN5mdiQqMQ",
    description:
      "Es el seudónim del patriota Ahn-Chan-Ho (1876-1938) que luchó por la educación e independencia de Corea. Los 24 movimientos representan su vida.",
    belt: "Amarillo punta Verde",
    diagram: "Z invertida",
    qtyMovements: 24,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [
		"Dezplazar el pie izquierdo a B formando una posicion de caminar, realizando una defenza alta a B con el canto externo del antebrazo izquierdo",
		"Manteniendo la posicion de caminar anterior, realizar un golpe de puño a altura media a B con el puño derecho", 
		"Desplazar el pie izquierdo sobre la linea AB y en seguida girar en el sentido horario, formando una posicion de caminar y realizando una defensa alta con el canto externo del antebrazo derecho", 
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media a A  con el puño izquierdo",
		"Desplazar el pie izquierdo a D, formando una posicion L, realizando una defensa media con el canto de mano izquierda",
		"Desplazar el pie derecho a D, formando una posicion de caminar, realizando un golpe con la piunta de los dedos de la mano derecha",
		"Girar la mano derecha junto con el cuerpo en sentido antihorario, hasta que la palma quede mirando al suelo (Para safar de un agarre). Luego trasladar el pie izquierdo a D, girando en sentido antihorario formando una posicion para caminar, realizando un golpe alto con el reverso del puño izquierdo", 
		"Desplazar el pie derecho a D, formando una posicion para caminar, realizando un golpe alto con el reverso del puño derecho",
		"Girando en sentido antihorario, desplazar el pie izquierdo a E, formando una posicion de caminar, realizando una defensa alta con el canto externo del antebrazo izquierdo",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media con el puño derecho",
		"Dezplazar el pie izquierdo sobre la linea EF,y girar en sentido horario, formando una posicion de caminar, realizando una defensa alta con el canto externo del antebrazo derecho",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media con el puño izquierdo",
		"Desplazar el pie izquierdo a CE ( Angulo de 45°), realizando una doble defensa alta con el canto externo de los antebrazos", 
		"Realizar una patada de frente a CE, con el pie derecho, manteniendo la posicion de los brazos", 
		"Bajar el pie derecho a CE, formando una posicion para caminar, dando un golpe de puño a altura media a CE con el puño derecho (Realizar movimiento 15 y16 de forma continua)",
		"Manteniendo la posicion, dar una golpe de puño a altura media con el puño izquierdo (Realizar movimiento 15 y16 de forma continua)",
		"Desplazar el pie derecho a CF, formando una posicion de caminar, realizando una doble defensa alta con el  canto externo de los antebrazos", 
		"Realizar una patada de frente a CF, con el pie izquierdo, manteniendo la posicion de los brazos",
		"Bajar el pie izquierdo a CF, formando una posicion de caminar, realizando un golpe de puño a altura media a CF con el puño derecho (Realizar movimiento 19 y 20 de forma continua)",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media con el puño derecho (Realizar movimiento 19 y 20 de forma continua)",
		"Desplazar el pie izquierdo a C, formando una posicion de caminar, realizando una defensa arriba con el antebrazo izquierdo",
		"Dezplazar el pie derecho a C, formando una posicion de caminar, realizando una defensa arriba con el antebrazo derecho",
		"Girando en sentido antihorario, desplazar el pie izquierdo a B, formando una posicion de jinete, realizando un golpe a altura media con canto de mano izquierda",
		"Llevar el pie izquierdo hacia el derecho, trasladar el pie derecho a A, realizando un golpe a altira media con canto de mano derecha" 
		"Traer el pie derecho Hacia la posicion inicial"
	],
    times: ["0m01.957s",
			"0m03.618s",
			"0m05.774s",
			"0m07.480s",
			"0m09.271s",
			"0m10.840s",
			"0m13.264s",
			"0m14.962s",
			"0m16.628s",
			"0m18.258s",
			"0m20.668s",
			"0m22.168s",
			"0m23.972s",
			"0m24.737s",
			"0m26.105s",
			"0m26.760s",
			"0m28.535s",
			"0m29.417s",
			"0m30.833s",
			"0m31.308s",
			"0m33.164s",
			"0m34.880s",
			"0m36.530s",
			"0m38.836s",
			"0m42.084s"
	],
  },
  wonhyo: {
    name: "Won-Hyo",
    gup: "Gup 6",
    video: "xjLmmyvNWT8",
    description:
      "Monje que introdujo el budismo durante la dinastía silla en el 686 A.C. (Antes de Cristo)",
    belt: "Verde",
    diagram: "Doble T",
    qtyMovements: 28,
    junbi: "Moa Sogi Junbi A",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [
		"Desplaxar el pie izquierdo a B formando una posicion en L, realizando una defensa doble a altura alta (Antebrazo derecho) y a altura media (Antebrazo izquierdo)",
		"Manteniendo la posicion L ,realizar un golpe alto hacia adentro a B (A la altura del cuello) con el canto de mano derecha, trayendo el puño izquierdo al hombro derecho como reaccion",
		"Realizar un golpe a altura media a B con el puño izquierdo, formando una posicion L con peso repartido a B deslizando el pie izquierdo a B",
		"Llevar el pie izquierdo hacia el derecho, dezplazar el pie derecho a A formando una posicion L, realizando una defensa doble a altura alta (Antebrezo izquierdo) y a altura media (Antebrazo derecho)",
		"Manteniendo la posicion L, realizar un golpe alto hacia adentro a A (A altura del cuelllo) con el canto de la mano izquierda, trayendo el puño derecho al hombro izquierdo como reaccion",
		"Realizar un golpe a altura media a A con el puño derecho, formando una posicion L con peso repartidoa a A deslizando el pie derecho a A",
		"Llevar el pie derecho hacia el izquierdo, mirar hacia D moviendo la cara realizando una posicion de lucha en una pierna (Goburyo sogi) sobre la pierna derecha",
		"Realizar una patada de costado a altura media, a D con el pie izquierdo",
		"Bajar el pie izquierdo a D, formando una posicion L, realizando una defensa a altura media a D con el canto de mano izquierda",
		"Desplazar el pie derecho a D, formando una posicion L, realizando una defensa a altura media a D con el canto de mano derecha",
		"Desplazar el pie izquierdo a D formando una posicion L, realizando una defensa a altura media a D, con canto de mano izquierda",
		"Desplazar el pie derecho a D, formando una posicion de caminar, realizando un ataque a altura media a D, con la punta de los dedos de la mando derecha, la mano izquierda baja para posicionarse debajo del codo",
		"Girando en sentido contrario a las agujas del reloj, desplazar el pie izquierdo a E, formando una posicion L realizando una doble defensa a altura alta (Antebrazo derecho) y altura media  (Antebrazo izquierdo)",
		"Manteniendo la posicion L ,realizar un golpe alto hacia adentro a E (A la altura del cuello) con el canto de mano derecha, trayendo el puño izquierdo al hombro derecho como reaccion",
		"Realizar un golpe a altura media a E con el puño izquierdo, formando una posicion L con peso repartido a E deslizando el pie izquierdo a E",
		"Llevar el pie izquierdo hacia el derecho, luego trasladar el pie derecho a F, formando una posicion L, realizando una doble defensa a altura alta (Antebrazo izquierdo) y a altura media (Antebrazo derecho)",
		"Manteniendo la posicion L, realizar un golpe alto hacia adentro a F (A la atura del cuello) con el canto de la mano izquierda, trallendo el puño derecho al hombro izquierdo como reaccion",
		"Dar un golpe a altura media a F con el puño derecho, formando una posicion L con peso repartido a F deslizando el pie derecho a F",
		"Traer el pie derecho hacia el izquierdo, luego trasladar el pie izquierdo a C, formando una posicion de caminar, realizando un bloqueo circular a CF, con la parte interna del antebrazo derecho",
		"Con el pie derecho, realizar una patada de frente baja a C, manteniendo la posicion de las manos igual que el movimiento 19",
		"Bajar el pie derecho a C, formando una posicion de caminar, realizando un golpe media a C con el puño izquierdo",
		"Manteniendo la posicion de caminar, realizar un bloqueo circular a CE con la parte interna del antebrazo izquierdo",
		"Con el pie izquierdo, realizar una patada de frente baja a C, manteniendo la posicion de las manos del movimiento 22",
		"Bajar el pie izquierdo a C, formando una posicion de caminar, realizando un golpe medio a C con el puño derecho",
		"Girar la cara hacia C, formando una posicion de lucha en una pierna (Goburyo sogi) sobre la pierna izquierda",
		"Realizar una patada de costado a altura media a C con el pie derecho",
		"Bajar el pie derecho sobre la linea CD, luego girando en sentido contrario a las agujas del reloj dezplazar el pie izquierdo a B, formando una posicion L realizando una posicion de lucha hacia B",
		"Traer el pie izquierdo hacia el derecho, desplazar el pie derecho a A, formando una posicion L, realizando una posicion de lucha a A",
		"Traer el pie derecho a una posicion preparatoria"
	],
    times: [
		"0m02.366s",
		"0m03.624s",
		"0m05.156s",
		"0m07.315s",
		"0m08.816s",
		"0m10.254s",
		"0m12.203s",
		"0m13.485s",
		"0m15.177s",
		"0m16.423s",
		"0m18.254s",
		"0m19.783s",
		"0m21.515s",
		"0m22.802s",
		"0m24.303s",
		"0m26.797s",
		"0m27.850s",
		"0m29.382s",
		"0m32.119s",
		"0m33.271s",
		"0m34.593s",
		"0m36.280s",
		"0m37.289s",
		"0m38.832s",
		"0m40.392s",
		"0m41.806s",
		"0m44.076s",
		"0m46.496s",
		"0m50.214s"
	],
  },
  yulgok: {
    name: "Yul-Gok",
    gup: "Gup 5",
    video: "ccOy9Z1hZVk",
    description:
      "Seudónimo del maestro Yil, apodado el “Confucio de corea”. Los 38 movimientos representan la latitud donde nació. El diagrama representa al maestro.",
    belt: "Verde punta Azul",
    diagram: "Cruz Escolástica",
    qtyMovements: 38,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [
		"Desplazar el pie izquierdo a B, formando una posicion de jinete a D, extendiendo el puño izquierdo a D horizontalmente",
		"Manteniendo la posicion de jinete, realizar un golpe de puño derecho a altura media a D (Realizar 2 y 3 de en un movimiento rapido)",
		"Manteniendo la posicion de jinete, realizar un golpe de puño izquierdo a altura media a D (Realizar 2 y 3 de en un movimiento rapido)",
		"Llevar el pie izquierdo hacia el derecho, luego dezplazar el pie derecho a A, formando una posicion de jinete mirando a D , extendiendo el puño derecho a D horizontalmente",
		"Manteniendo la posicion de jinete, realizar un golpe de puño izquierdo a altura media a D (Realizar 5 y 6 en un movimiento rapido)",
		"Manteniendo la posicion de jinete, realizar un golpe de puño derecho a altura media a D (Realizar 5 y 6 en un movimiento rapido)",
		"Trasladar el pie derecho a AD, formando una posicion para caminar, realizando un bloqueo medio a AD, con la parte interna del antebrazo derecho",
		"Realizar una patada de frente a AD con el pie izquierdo, manteniendo la posicion de las manos del movimiento anterior",
		"Bajar el pie izquierdo a AD, formando una posicion de caminar, realizando un golpe de puño a altura media a AD con el puño izquierdo  (Realizar 9 y 10 en un movimiento rapido)",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media con el puño derecho (Realizar 9 y 10 en un movimiento rapido)",
		"Desplazar el pie izquierdo a BD, formando una posicion de caminar, realizando un bloqueo medio a BD con la parte interna del antebrazo izquierdo",
		"Realizar una patada de frente a AD con el pie derecho, manteniendo la posicion de las manos del movimiento anterior",
		"Bajar el pie derecho a BD formando una posicion de caminar, realizando un golpe a altura media a BD con el puño derecho (realizar 13 y 14 en un movimiento rapido)",
		"Manteniendo la posicion de caminar, realizar un golpe de puño medio a BD con el puño izquierdo (Realizar 13 y 14 en un movimiento rapido)",
		"Girando sobre el pie iizquierdo, formar una posicion de caminar, realizando una defensa de agarre a altura media a D con la palma de la mano derecha",
		"Manteniendo la posicion de caminar, realizar una defensa de agarre a altura media a D con la palma de la mano izquierda (Realizar 16 y 17 en un movimieno conectado)",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a D con la mano derecha (Realizar 16 y 17 en un movimieno conectado)",
		"Desplazar el pie izquierdo a D, formando una posicion de caminar, realizando una defensa de agarre a altura media a D con la palma de la mano izquierda",
		"Manteniendo la posicion de caminar, realizar una defensa de agarre a altura media a D con la palma de la mano derecha (Realizar 19 y 20 en un movimiento conectado)", 
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media a D con el puño Izquierdo (Realizar 19 y 20 en un movimiento conectado)",
		"Desplazar el pie derecho a D, formando una posicion de caminar, realizando un golpe de puño a altura media con el puño derecho",
		"Girar la cara a D, formando una posicion de lucha en una pierna (sobre la pierna derecha)",
		"Realizar una patada de costado a D con el pie izquierdo, manteniendo la posicion de las manos del movimiento anterior",
		"Bajar el pie izquierdo a D, formando una posicion de caminar, golpeando la palma izquierda con la parte anterior del codo derecho",
		"Girar la cara a C, formando una posicion de lucha en una pierna (Sobre el pie derecho)",
		"Realiza una patada de costado a C con el pie izquierdo, manteniendo la posicion de las manos del movimiento anterior",
		"Bajar el pie derecho a C, formando una posicion de caminar, golpeando la palma derecha con el codo aanterior izquierdo",
		"Desplazar el pie izquierdo a E, formando una posicion L, realizanfdo una doble defensa (A altura alta y media) con el canto de ambas manos",
		"Desplazar el pie derecho a E formando una posicion de caminar, realizando un golpe a altura media a E con la punta de los dedos de la mano derecha",
		"Girando en sentido horario, desplazar el pie derecho a Fformando una piosicion L, realizando una doble derensa (A altura alta y media) con el canto de ambas manos",
		"Desplazar el pie izquierdo a F formando una posicion de caminar, realizando un golpe a altura media a F con la pinta de los dedos de la mano izquierda",
		"Desplazar el pie izquierdo a C formando una posicion de caminar,realizando un bloqueo alto con el canto externo del antebrazo izquierdo", 
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media a C con el puño derecho",
		"Desplazar el pie derecho a C formando una posicion de caminar, realizando un bloqueo alto a C con el canto externo del antebrazo derecho",
		"Manteniendo la posicion de caminar, realizar un golpe de puño a altura media a C con el puño izquierdo",
		"Saltar a C (Distancia equivalente a un paso) formando una posicion en X a B, Dando un golpe alto a C con el reverso del puño izquierdo", 
		"Desplazar el pie derecho a A formando una posicion de caminar, realizando un bloqueo alto a A con la parte interna del antebrazo derecho, llevando el puño izquierdo al codo derecho",
		"Llevar el pie derecho junto al izquierdo, luego desplazar el pie izquierdo a B formando una posicion de caminar, realizando un bloqueo alto a B con la parte interna del antebrazo izquierdo, llevando el puño derecho al codo izquierdo",
		"Llevar el pie izquierdo a una posicion preparatoria"
	],
    times: [
		"0m02.833s",
		"0m04.102s",
		"0m04.608s",
		"0m06.989s",
		"0m08.099s",
		"0m08.734s",
		"0m10,294s",
		"0m11.304s",
		"0m12.464s",
		"0m12.974s",
		"0m14.793s",
		"0m15.728s",
		"0m16.925s",
		"0m17.430s",
		"0m19.588s",
		"0m20.755s",
		"0m21.675s",
		"0m23.155s",
		"0m24.634s",
		"0m25.477s",
		"0m27.081s",
		"0m28.470s",
		"0m29.351s",
		"0m31.250s",
		"0m32.656s",
		"0m33.520s",
		"0m35.431s",
		"0m37.203s",
		"0m38.784s",
		"0m40.450s",
		"0m42.258s",
		"0m43.826s",
		"0m45.122s",
		"0m46.914s",
		"0m48.602s",
		"0m50.285s",
		"0m52.121s",
		"0m54.731s",
		"0m58.489s"
	],
  },
  joonggun: {
    name: "Joong-Gun",
    gup: "Gup 4",
    video: "Lc3aI94y1JM",
    description:
      "Se opuso a la fusión de Corea-Japón. Los 32 movimientos representan la edad a la que murió.",
    belt: "Azul",
    diagram: "Doble T",
    qtyMovements: 32,
    junbi: "Moa Junbi Sogi B",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [],
    times: [],
  },
  toigye: {
    name: "Toi-Gye",
    gup: "Gup 3",
    video: "P_6i96pDZLw",
    description:
      "Seudónimo de Yi Hang, una autoridad del neo confucionismo. Los 37 movimientos representan la latitud donde nació. El diagrama representa al maestro.",
    belt: "Azul punta Roja",
    diagram: "Cruz Escolástica",
    qtyMovements: 37,
    junbi: "Moa Junbi Sogi B",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  hwarang: {
    name: "Hwa-Rang",
    gup: "Gup 2",
    video: "m7UEsVD-hpg",
    description:
      "Grupo de jóvenes guerreros creados durante la dinastía silla hace más de 1350 años, al comienzo del siglo VII. Los 29 movimientos hacen referencia a la división 29 de infantería, donde el Taekwondo alcanzó su madurez.",
    belt: "Rojo",
    diagram: "Doble T",
    qtyMovements: 29,
    junbi: "Moa Junbi Sogi C",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  choongmoo: {
    name: "Choong-Moo",
    gup: "Gup 1",
    video: "L35mUDanJtc",
    description:
      "Seudónimo del almirante Yi son-sin de la dinastía Yi. Se le atribuye haber inventado la primera nave de combate blindada en 1592, la que sería precursora del submarino. El tul finaliza con un ataque con la mano izquierda para simbolizar tu tremenda muerte, por la que no tuvo tiempo de demostrar su lealtad al rey.",
    belt: "Rojo punta Negra",
    diagram: "Doble T",
    qtyMovements: 30,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [],
    times: [],
  },
  kwangae: {
    name: "Kwang-Gae",
    dan: "I Dan",
    video: "yjX_nw31m-4",
    description:
      "Kwang-Gae-Toh-Wang que fue el 19 rey de la Dinastía Koguryo que reconquistó todos los territorios perdidos incluyendo la mayor parte de Manchuria. El diagrama representa la expansión y recuperación del territorio perdido. Los 39 movimientos se refiere a su reinado de 39 años.",
    belt: "Negro I DAN",
    diagram: "",
    qtyMovements: 39,
    junbi: "Narani so Hanulson",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [
      "Levar el pie izquierdo hacia el derecho formando una posicion preparatoria de pies juntos B (Moa sogi B) a D Moviendo las manos en un movimiento circular",
      "Desplazar el pie izquierdo a D formando una posicion para caminar, realizando un golpe en forma de gancho con el puño derecho (Realiarlo lentamente)",
      "Desplazar el pie derecho a D formando una posicion para caminar, realizando un golpe en forma de gancho con el puño izquierdo (Realizarlo lentamente)",
      "(Movimiento de traslado de 2 pasos) Desplazar el pie izquierdo a la parte delantera lateral del pie derecho, luego traslada el pue derecho a D formando una posicion para caminar realizando un bloqueo de agarre descendente con la palma derecha",
      "Desplazar el pie derecho a C (En un deslizamiento hacia atras) para formar una posicion en 'L' (Mirando a D) Realizando un bloqueo bajo con canto de mano",
      "(Movimiento de traslado de 2 pasos) Desplazar  el pie derecho hacia la parte delantera lateral del pie izquierdo, luego desplazar el pie izquierdo a D formando una posicion para caminar realizando un bloqueo alto de agarre decendente con la palma izquierda",
      "Desplazar el pie izquierdo a C (En un deslizamiento hacia atras) para formar una posicion en 'L' (Mirando a D) Realizando un  bloqueo bajo con canto de mano",
      "Desplazar el pie izquierdo a D formando una posicion en L corta realizando un bloqueo alto con canto de mano izquierda",
      "Desplazar el pie derecho a D formando una posicion en 'L' corta realizando un bloqueo alto con canto de mano derecha",
      "Desplazar el pie izquierdo hacia la parte delantera lateral del pie derecho, girar sobre el pie izquierdo (NO se mueve, solo gira) en sentido de las agujas del reloj (Por delante)  formando una posicion para caminar, realizando un bloqueo ascendente (A altura media) con la palma derecha (Realizarlo lentamente)",
      "Desplazar el pie derecho a C formando una posicion para caminar, realizando un bloqueo ascendente con palma izquierda (Realizarlo lentamente)",
      "Dezplazar el pie izquierdo para formar una posicion de pies juntos, realizar un movimiento circular para llegar a un bloqueo bajo con canto de mano derecha (Mano derecha paralela al cuerpo y la izquierda perpendicular a esta)",
      "Con el pie izquierdo dar una patada de presion (Altura de la rodilla) a E (manteniendo la posicion de las manos del movimiento 12)",
      "Con el pie izquierdo dar una patada lateral a altura media a E (manteniendo la posicion de las manos)",
      "Bajar el pie izquierdo a E formando una posicion 'L', dar un golpe alto con canto de mano derecha. el puño izquierdo se dirige al hombro derecho",
      "Con el puño izquierdo dar un golpe descendente a E formando una posicion de pies juntos mirando a C",
      "Con el pie derecho dar una patada de presion a F (Manteniendo la posicion de las manos del movimiento 16)",
      "Con el pie derecho dar una patada lateral a altura media a F (Manteniendo la posicion de las manos del movimiento 16)",
      "Bajar el pie derecho a F formando una posicion 'L' dando un golpe alto con canto de mano izquierda, el puño derecho se dirige al hombro izquierdo",
      "Con el puño derecho dar un golpe descendente a F formando una posicion de pies juntos mirando a C",
      "Dezplazar el pie izquierdo a C formando una posicion para caminar baja, realizando un bloqueo por presion con la palma derecha (Noollo Makgi)(Se realiza lentamente)",
      "Desplazar el pie derecho a C formando una posicion para caminar baja realizando un bloqueo por precion con palma izquierda (se realiza lentamente)",
      "Dezplazar el pie derecho a D formando una posicion de jinete (Mirando a F) Dando un golpe later alto a D con el reverso del puño derecho",
      "Con un doble antebrazo interno derecho realizar un bloquieo medio a D cambiando a una posicion para caminar moviendo la pierna derecha(con pierna derecha adelante)",
      "Con el antebrazo izquierdo realizar un bloqueo lateral bajo hacia D manteniendo la posicion para caminar (Movimiento 24)",
      "Con la punta de los dedos de la mano derecha realizar un golpe alto a D formando una posicion para caminar baja, deslizando el pie derecho",
      "Dezplazar el pie izquierdo sobre la linea B-C para formar una posicion de jinete mirando a F, dando un golpe lateral alto a C con el reverso del puño izquierdo",
      "Con un doble antebrazo interno izquierdo realizar un bloqueo medio a C cambiando a una posicion para caminar apoyandose sobre el pie izquierdo",
      "Con el antebrazo derecho realizar un bloqueo lateral bajo a C deslizandose levemente a D, manteniendo la pisicion para caminar (Movimiento 28)",
      "Con la punta de los dedos de la mano izquierda realizar un golpe alto a C formando una posicion para caminar baja deslizando el pie izquierdo",
      "Con un pisoton mover el pie derecho a C formando una posicion para caminar, dando un golpe alto con ambos puños verticales",
      "Con un pisoton mover el pie izquierdo a A formando una posicion para caminar dando un golpe bajo en forma de gancho con ambos puños",
      "Con el pie derecho dar una patada frontal media a A manteniendo las manos como el movimiento anterior",
      "Bajar el pie derecho hacia el izquierdo, desplazar el pie izquierdo a A formando una posicion en 'L' mirando a B realizando un bloquueo medio con canto de mano derecha",
      "Desplazar el pie izquierdo a B formando una posicion para caminar dando un golpe de puño alto izquierdo a B",
      "Con un pisoton desplazar el pie derecho a B formando una posicion para caminar dando un golpe bajo en forma de gancho cn ambos puños",
      "Con el pie izquierdo dar una patada frontal media a B, manteniendo las manos como en el movimiento anterior",
      "Bajar el pie izquierdo hacia el derecho, dezplazar el pie derecho a B para formar una posicion en 'L' mirando a  A realizando un bloqueo medio con canto de mano izquierda",
      "Dezplazar el pie derecho a A formando una posicion para caminar dando un golpe de puño alto derecho a A",
      "Llevar el pie izquierdo a la posicion preparatoria",
    ],
    times: [
      "0m04.619s",
      "0m08.115s",
      "0m11.776s",
      "0m13.749s",
      "0m15.383s",
      "0m17.211s",
      "0m18.863s",
      "0m20.419s",
      "0m22.334s",
      "0m25.402s",
      "0m11.776s",
      "0m13.749s",
      "0m15.383s",
      "0m17.211s",
      "0m18.863s",
      "0m20.419s",
      "0m22.334s",
      "0m25.402s",
      "0m28.848s",
      "0m30.515s",
      "0m31.068s",
      "0m31.922s",
      "0m33.427s",
      "0m34.593s",
      "0m35.595s",
      "0m36.649s",
      "0m38.105s",
      "0m39.297s",
      "0m42.391s",
      "0m45.824s",
      "0m47.585s",
      "0m48.834s",
      "0m49.806s",
      "0m53.221s",
      "0m55.071s",
      "0m56.507s",
      "0m57.243s",
      "1m0.902s",
      "1m02.543s",
      "1m04.013s",
      "1m05.047s",
      "1m06.861s",
      "1m08.511s",
      "1m10.145s",
      "1m10.987s",
      "1m12.921s",
      "1m14.423",
      "1m18.719",
    ],
  },
  poeum: {
    name: "Po-Eum",
    dan: "I Dan",
    video: "RE2mg_pu-BI",
    description:
      "Es el pseudónimo de un súbdito leal, Chong Mong-Chu (1400 D.C) que fue un famoso poeta que decía 'Yo no serviría a un segundo amo aunque fuera crucificado 100 veces' es conocido por todo coreano. Fue pionero en el campo de la física. El diagrama representa su lealtad inequívoca al rey y al país, hacia el fin de la Dinastía Koryo.",
    belt: "Negro I DAN",
    diagram: "Línea recta (horizontal)",
    qtyMovements: 36,
    junbi: "Narani so Hanulson",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [
      "Desplazar el pie izquierdo a B formando una posicion en 'L' realizando un bloqueo a altura media con antebrazo izquierdo",
      "Llevar el pie derecho a la articulacion de la rodilla izquierda formando una posicion de un solo pie, levantar los puños y girando la cara mirando a A",
      "Dar una patada de presion (Altura de la rodilla) a A manteniendo la posicion de las manos del movimiento anterior",
      "Bajar el pie derecho a A formando una posicion de jinete (mirando a D) dando un golpe a altura media con canto de mano derecha",
      "Conservando la posicion de jinete, con el puño izquierdo dar un golpe en angulo",
      "Conservando la posicion de jinete,realizar un bloqueo por presion con el puño izquierdo, realizando un bloqueo frontal lateral con el antebrazo derecho",
      "Conservando la posicion de jinete realizar un bloqueo por presion con el puño derecho, realizando un bloqueo frontal laterac con el antebrazo izquierdo",
      "Manteniendo la posicion de jinete realizar un bloqueo medio doble con los antebrazos internos paralelos",
      "Manteniendo la poscion de jinete golpear a C con el codo derecho, llevando la palma izquierda al puño derecho",
      "Manteniendo la posicion de jinete realizar un golpe de puño derecho a altura media a D, deslizando la palma izquierda la articulacion del codo derecho",
      "Manteniendo la poscion de jinete golpear a C con el codo izquierdo, llevando la palma derecha al puño izquierdo",
      "Manteniendo la posicion de jinete dar un golpe horizontal con puño derecho a A",
      "Cruzar el pie izquierdo por delante del derecho formando una posicion en 'X' (Mirando a D) realizando un bloqueo frontal bajo con el antebrazo externo derecho, llevar la punta de los dedos de la mano izquierda sobre el antebrazo derecho",
      "Desplazar el pie derecho a A formando una posicion en 'L' realizando un agarre en forma de 'U' (Ambas palmas apuntan hacia arrba)",
      "Llevar el pie izquierdo junto al pie decho formando una posicion de pies juntos realizando un golpe orizontal con ambos codos, girando la cara a B (Realizarlo lentamente)",
      "Desplazar el pie izquierdo a B formando una posicion de jinete, dando un golpe lateral a C con el reverso del puño derecho, extendiendo el brazo izquierdo lateralmente bajo",
      "Cruzar el pie derecho por delante del izquierdo formando una posicion en 'X' realizando un bloqueo frontal bajo con el antebrazo externo izquiero, llevando la punta de los dedos de la mano derecha al lateral del puño izquierdo",
      "Dezplazar el pie izquierdo a B formando una posicion de jinete realizando un bloqueo bajo doble con el reverso de canto de mano (Ambas palmas miran hacia arriba)",
      "Moviendo el pie derecho formar una posicion en 'L' realizando un bloqueo medio con antebrazo derecho",
      "Llevar el pieizquierdo a la articulacion de la rodilla derecha formando una posicion de un solo pie, levantando los puños y moviendo la cara a B",
      "Dar una parada de presion a B (Altura de la rodilla) manteniendo la posicion de las manos del movimiento anterior",
      "Bajar el pie izquierdo a B formando una posicion de jinete dando un golpe a altura media con canto de mano izquierda",
      "Manteniendo la posicion de jinete dar un golpe en angulo con el puño derecho",
      "Manteniendo la posicion de jinete dar un golpe de presion con el puño derecho y un bloqueo frontal lateral con el antebrazo izquierdo",
      "Manteniendo la posicion de jinete realizar un bloqueo de presion con el puño izquierdo y un bloqueo frontal lateral con el antebrazo derecho",
      "Manteniendo la posicion de jinete realizar un bloqueo medio doble con los antebrazos paralelos",
      "Manteniendo la posicion de jinete golpear a C con el codo izquierdo llevando la palma derecha al puño izquierdo",
      "Manteniendo la posicion de jinete realizar un golpe de puño izquierdo a altura media a D, deslizando la palma derecha a la articulacion del codo izquierdo",
      "Manteniendo la posicion de jinete golpear a C con el codo derecho llevando la palma izquierda al puño derecho",
      "Manteniendo la posicion de jinete dar un golpe horizontal con puño izquierdo a B",
      "Cruzar el pie derecho por delante del izquierdo formando una posicion en 'X' realizando un bloqueo bajo con el antebrazo izquierdo, llevar la punta de los dedos de la mano derecha sobre el antebrazo derecho",
      "Dezplazar el pie izquierdo a b formando una posicion en 'L' realizando un agarre en forma de 'U' (Ambas palmas apuntan hacia arriba)",
      "Llevar el pie derecho hacia el izquierdo formando una posicion de pies juntos realizando un golpe horizontal con ambos codos girando la cara a A (se realiza lentamente)",
      "Desplazar el pie derecho a A para formar una posicion de jinete realizando un golpe lateral a C con el reverso del puño izquierdo, extendiendo el brazo derecho hacia abajo y lateralmente",
      "Cruzar el pie izquierdo por delante del derecho formando una posicion en 'X' realizando un bloqueo lateral bajo con el antebrazo derecho llevando la parte inferior de los dedos de la mano izquierda al puño derecho",
      "Desplazar el pie derecho a A formando una posicion de jinete realizando un bloqueo bajo doble con reverso de canto de mano (Ambas palmas miran hacia arriba)",
      "Llevar el pie izquierdo a la posicion preparatoria",
    ],
    times: [
      "0m02.755s",
      "0m03.682s",
      "0m04.291s",
      "0m06.159s",
      "0m07.643s",
      "0m09.031s",
      "0m09.671s",
      "0m10.279s",
      "0m10.812s",
      "0m11.534s",
      "0m12.121s",
      "0m12.906s",
      "0m14.635s",
      "0m16.140s",
      "0m18.730s",
      "0m20.559s",
      "0m21.938s",
      "0m23.564s",
      "0m25.160s",
      "0m25.954s",
      "0m26.610s",
      "0m28.325s",
      "0m29.801s",
      "0m30.988s",
      "0m31.506s",
      "0m32.170s",
      "0m32.660",
      "0m33.327",
      "0m34.557s",
      "0m36.113s",
      "0m36.113",
      "0m37.755",
      "0m40.115",
      "0m41.825",
      "0m43.438",
      "0m45.081",
      "0m48.892",
    ],
  },
  gebaek: {
    name: "Ge-Baek",
    dan: "I Dan",
    video: "SHcNcUaaxv8",
    description:
      "Recibe el nombre de Ge-Baek gran general de la dinastía Baek Je. El diagrama representa su severa y estricta disciplina militar.",
    belt: "Negro I DAN",
    diagram: "Línea recta (vertical)",
    qtyMovements: 44,
    junbi: "Narani Junbi Sogi",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  euiam: {
    name: "Eui-Am",
    dan: "II Dan",
    video: "inMKh0lC_KI",
    description:
      "Es el pseudónimo de SibByong Hi, líder del movimiento de independencia de Corea (10 de Marzo de 1919). Los 45 movimientos se relacionan con su edad cuando cambió el nombre de Dong Hak( Cultura Oriental) por el de ChondoKyo (Religión de los Caminos del Cielo) en 1905. El diagrama representa su indomable espíritu dedicado a la prosperidad de su nación.",
    belt: "Negro II DAN",
    diagram: "Línea recta (vertical)",
    qtyMovements: 45,
    junbi: "Narani Junbi Sogi D",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  choongjang: {
    name: "Choong-Jang",
    dan: "II Dan",
    video: "cWZL2LErGTg",
    description:
      "Es el pseudónimo dado al General Kim DukRyang que vivió durante la Dinastía Yi en el siglo XV. Este modelo termina con un ataque de mano izquierda que simboliza la tragedia de su muerte en prisión a los 27 años, antes de lograr su plena madurez.",
    belt: "Negro II DAN",
    diagram: "",
    qtyMovements: 52,
    junbi: "Narani Junbi Sogi D",
    start: "Pie derecho",
    finish: "Pie izquierdo",
    movements: [],
    times: [],
  },
  juche: {
    name: "Juche",
    dan: "II Dan",
    video: "1tOwFhxw4FE",
    description:
      "Es una idea filosófica que el hombre es el amo de todo y decide todo. Es decir que el hombre es el amo del mundo y de su propio destino. Esta idea se dice fue sacada en la montaña de Baekdu que simboliza el espíritu de la gente coreana. El modelo representa la montaña de Baekdu.",
    belt: "Negro II DAN",
    diagram: "",
    qtyMovements: 45,
    junbi: "",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  choiyong: {
    name: "Choi-yong",
    dan: "III Dan",
    video: "PZXdNG3Bs4U",
    description:
      "El nombre proviene del General Choi Yong comandante en Jefe de las Fuerzas Armadas durante el Siglo XIV en la Dinastía Koryo,muy respetado por su lealtad, patriotismo y humildad. Fue ejecutado por sus comandantes subordinados encabezados por el General YiSungGae que después se convirtió en el primer rey de la Dinastía Yi",
    belt: "Negro III DAN",
    diagram: "Cruz",
    qtyMovements: 46,
    junbi: "Narani Junbi Sogi C",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [
      "Dezplazar el pie izquierdo a D formando una poscion L corta realizando un bloqueo en guardia a altura media a D con antebrazo izquierdo",
      "Manteniendo la posicion L realizar un golpe alto a D con la falange del dedo medio izquierdo",
      "Dezplazar el pie izquierdo sobre la linea CD formando una posicion L corta (Mirando a C) realizando un bloqueo en guardia a altira media con el antebrazo derecho",
      "Manteniendo la posicion L dar un golpe alto con la falange del dedo medio derecho",
      "Dezplazar el pie derecho a la linea CD formando una posicion para caminar izquierda (Mirando a D) realizando un bloqueo alto con el canto de la mano izquierda",
      "Manteniendo la posicion para caminar realizar un bloqueo circular con el antebrazo interno derecho (Dolimyo makgi)",
      "Manteniendo la posicion de caminar realizar un golpe medio a D con el puño izquierdo",
      "Desplazar el pie izquierdo sobre la linea CD formando una poscion para caminar derecha (Mirando a C) realizando un bloqueo arriba con el canto de la mano derecha",
      "Manteniendo la posicion para caminar realizar una defensa circular con el antebrazo interno izquierdo",
      "Manteniendo la posicion para caminar car un golpe medio a C con el puño derecho",
      "Desplazar el pie derecho a la linea CD formando una poscion L derecha  realizando un bloqueo de guardia bajo a D con canto de mano",
      "Con el pie derecho realizar una patada circular media a AD luego bajarlo al lado frontal del pie izquierdo",
      "Dar un giro de talo en gancho alto a D con el pie izquierdo (Realizar 13 y 14 como patada consecutiva)",
      "Realizar una patada lateral media a D con el pie izquierdo llevando las manos a la direccion opuesta (Realizar 13 y 14 como patada consecutiva)",
      "Bajar el pie izquierdo a D para formar una posicion para caminar golpeando la palma isquierda con la parte frontal del codo derecho",
      "Desplazar el pie izquierdo sobre la linea CD formando una poscion L (Mirando a C) realizando un bloqueo en guardia bajo con canto de mano",
      "Con el pie izquierdo ralizar una patada circular media a AC luego bajarlo al lado frontal del pie derecho (Realizar 17 y 18 en forma consecutiva)",
      "Realizar un giro talon en gancho alto a C con el pie derecho (Realizar 17 y 18 en forma consecutiva)",
      "Sin bajar la pierna dar una patada lateralmedia a C con el pie derecho llevando las manos a la direccion contraria",
      "Bajar el pie derecho a C formando una posicion para caminar (Mirando a C) golpeando la palma derecha con la parte anterior del codo izquierdo",
      "Dezplazar el pie izquierdo a C formando una posicion para caminar realizando un bloqueo por presion con la palma derecha (Nollo makgi) (Realizar 21 y 22 en un movimiento rapido)",
      "Desplazar el pie derecho a C formando una posicion para caminar realizando un bloqueo por presion con la palma izquierda (Realizar 21 y 22 en un movimiento rapido)",
      "Desplazar el pie derecho a D (Hacia atras, posicionandolo levemente atras del izquierdo) girar sobre el pie derecho en sentido contrario a las agujas del reloj llevando el pie izquierdo a D formando una posicion para caminar (Mirando a D) realizando un bloqueo en forma de W con el canto de ambas manos",
      "Manteniendo la posicion de las manos dar una patada de frente al medio con el pie derecho ",
      "Bajar el pie derecho a C (Mirando a D) formando una posicion L realizando un bloqueo en guardia medio con el antebrazo izquierdo",
      "Desplazar el pie derecho a D formando una posicion para caminar realizando un bloqueo en forma de W con el canto de ambas manos",
      "Manteniendo la posicion de las manos dar una patada de frente con el pie izquierdo",
      "Bajar el pie izquierdo a D formando una posicion L (Mirando a C) realizando un bloqueo en guardia media con el antebrazo derecho",
      "Dezplazar el pie izquierdo a C, y el pie derecho a C luego deslizar a C girando en sentido de las agujas del reloj para formar una posicion L (Pierna derecha adelante y mirando a D) realizando un bloqueo en guardia media con el antebrazo derecho",
      "Dezplazar el pie izquierdo a D formando una posicion para caminar realizando un golpe alto a D con la punta de los dedos de la mano izquierda",
      "Desplazar el pie izquierdo sobre la linea CDformando una posicion para caminar (Mirando a C) realizando un golpe alto a C con la punta de los dedos de la mano derecha",
      "Desplazar el pie derecho a D girando en sentido de las agujas del reloj formando una posicion de pies paralelos (Mirando a B) realizando un bloqueo de agarre descendente a B con palma derecha (Realizar movimiento 32 y 33 de forma continuada)",
      "Manteniendo la posicion de pies paralelos dar un golpe medio a B con el puño izquierdo",
      "Girar la cara a A formando una posicion preparatoria de una pierna (Goburyo Sogi) mirando a A",
      "Realizar una patada lateral media a A con el pie derecho formando un bloqueo en guardia con el antebrazo derecho",
      "Bahar el pie derecho a A, saltando formar una posicion en X a AD realizando un golpe lateral lato a A con el reverso del puño derecho, llevar la parte inferior de los dedos de la mano izquierda al puño lateral derecho",
      "Realizar un golpe de talon en gancho a B con el pie derecho",
      "Con un pisoton bajar el pie derecho a B formando una posicion L dando un golpe hacia afuera a altura media con el canto de la mano derecha",
      "Desplazar el pie izquierdo a D girando en sentido contrario a las agujas del reloj para formar una posicion de pies paralelos (Mirando a A) realizando un bloqueo de agarre medio con la palma izquierda (Realizar 39 y 40 en un movimiento continuado)",
      "Manteniendo la posicion de pies paralelos realizar un golpe medio a A con el puño derecho",
      "Girar la cara a B formando una posicion perparatoria de un solo pie con pierna izquierda flexionada (Mirando a B)",
      "Realizar una patada lateral media a B con el pie izquierdo formando un bloqueo en guardia con el antebrazo izquierdo",
      "Con un salto bajar el pie izquierdo a B formando una posicion en X (Mirando a B) realizando un golpe lateral alto a B con el reverso del puño izquierdo llevando la parte inferior de los dedos de la mano derecha sobre el puño lateral izquierdo",
      "Realizar un giro talon en gancho alto hacia A con el pie izquierdo",
      "Con un pisoton bajar el pie izquierdo a A formando una posicion en L (Mirando a A) dando un golpe hacia afuera a altura media con canto de mano",
      "Deslizar a A para formar una posicion L peso repartido derecha(Pierna derecha adelante) dando un golpe a altura media a A con el puño derecho",
      "Llevar el pie derecho a una posicion preparatoria",
    ],
    times: [
      "0m02.537s",
      "0m03.927s",
      "0m05.940s",
      "0m07.418s",
      "0m09.110s",
      "0m10.554s",
      "0m12.114s",
      "0m14.120s",
      "0m15.779s",
      "0m17.357s",
      "0m19.431s",
      "0m20.497s",
      "0m21.965s",
      "0m22.729s",
      "0m24.315s",
      "0m26.362s",
      "0m27.321",
      "0m28.846s",
      "0m29.457s",
      "0m31.497s",
      "0m32.623s",
      "0m33.447s",
      "0m35.976s",
      "0m36.790s",
      "0m38.555s",
      "0m40.138s",
      "0m41.006s",
      "0m43.016s",
      "0m45.593s",
      "0m47.456s",
      "0m49.497s",
      "0m50.762s",
      "0m52.054s",
      "0m53.762s",
      "0m54.844s",
      "0m56.443",
      "0m57.308s",
      "0m58.768s",
      "1m00s",
      "1m00.928s",
      "1m02.799s",
      "1m03.523s",
      "1m05.071s",
      "1m06.189s",
      "1m07.823s",
      "1m09.493s",
      "1m13.661s",
    ],
  },
  samil: {
    name: "Sam-Il",
    dan: "III Dan",
    video: "xG4uBuH4NCE",
    description:
      "Denota la fecha histórica del movimiento de independencia de Corea que comenzó el 1o de Marzo de 1919.Posee 33 movimientos y representa a los 33 patriotas que planearon el movimiento.",
    belt: "Negro III DAN",
    diagram: "Cruz",
    qtyMovements: 33,
    junbi: "Narani Junbi Sogi C",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [
      "Desplazar el pie izquierdo a D formando una posicion L realizando un bloqueo medio con antebrazo izquierdo",
      "Desplazar el pie derecho a D formando una posicion para caminar realizando un bloqueoalto a D con doble antebrazo derecho",
      "Desplazar el pie izquierdo a D formando una posicion para caminar, realizando un bloqueo alto a D con canto de mano derecha, llevar la palma izquierda sobre la muñeca derecha",
      "Realizar una patada con metatarso hacia afuera con el pie derecho, manteniendo la posicion de las manos",
      "Bajar el pie derecho a D formando una posicion de caminar, realizando un golpe de puño derecho a altura media a D",
      "Desplazar el pie derecho sobre la linea CD para formar una posicion de jinete (Mirando a B) realizando un bloqueo a altura media con el reverso de canto de ambas manos",
      "Girando sobre el pie derecho formar una posicion para caminar (Mirando a C), ejecutando un golpe bajo con la punta de los dedos de la mano derecha",
      "Formar una posicion L trayendo el pie derecho (Mirando a C), realizando un bloqueo alto hacia atras y afuera a D con el antebrazo externo derecho y un bloqueo bajo a C con el antebrazo izquierdo",
      "Desplazar el pie derecho a C formando una posicion de jinete (Mirando a A) realizando un bloqueo a altura mdeia con el reverso de conto de ambas manos",
      "Fortmando una posicion L (Mirando a C) trayendo el pie derecho dar un golpe bajo a C con doble puño derecho",
      "Desplazar el pie izquierdo a C formando una posicion para caminar realizando un bloqueo alto a BC con doble mano en arco, mirando a traves de ellas",
      "Dezplazar el pie derecho a C formando una posicion para caminar, realizando un golpe a altura media con el puño izquierdo",
      "Desplazar el pie derecho sobre la linea CD, formando una posicion L (Mirando a D) realizando un golpe bajo a D con doble puño izquierdo",
      "Desplazar el pie derecho a B, realizando un bloqueo alto en guardia con el reverso de canto de mano izquierda",
      "Moviendo unicamente el pie izquierdo formar una posicion L con peso repartido izquierda realizar un bloqueo en U (Con palmas enfrentadas) a B",
      "Realizar una patada barriendo a B con el canto interno del pie derecho. bajar el pie derecho a B formando una posicion en L con peso repartido derecha realizando un bloqueo en U (Palmas enfrentadas) a B",
      "Saltar girando en sentido contrario a las agujas del reloj bajando en el mismo lugar formando una posicion L realizando un bloqueo medioa a B con canto de mano",
      "Realizar una patada lateral media a B con el pie derecho realizando un bloqueo en guarfia con canto de mano",
      "Bajar el pie derecho junto al izquierdo desplazar el pie izquierdo a A formando una posicion para caminar golpeando la palma izquierda con el codo frontal derecho",
      "Dezplazar el pie derecho a A girando en sentido contrario de las agujas del reloj realizando un golpe a C con la parte trasera del codo izquierdo, sosteniendo el puño izquierdo con la palma derecha y otando a C",
      "Formando una posicion para caminar a AD realizar un bloqueo por presion con los puños en X",
      "Con un pisoton desplazar el pie izquierdo a A realizando un bloqueo en W con el antebrazo externo izquierdo",
      "Realizar una patada lateral media a A con el pie izquierdo realizando un bloqueo en guardia con el antebrazo",
      "Bajar el pie izquierdo a A formando una posicion en L realizando un bloqueo en guardia bajo con canto de mano a B",
      "Desplazar el pie izquierdo a B formando una posicion en L corta realizando un bloqueo ascendente con la palma izquierda",
      "Desplazar el pie derecho a B formando una posicion L corta realizando un bloqueo de presion con las palmas juntas descendentes",
      "Con un pisoton desplazar el pie izquierdo a C dando un golpe en forma de gancho a C con ambos puños",
      "Desplazar el pie decho a C formando una posicion L realizando un bloqueo bajo a C con el antebrazo derecho, llevando el puño izquierdo bajo la axila izquierda",
      "Manteniendo la posicion en L realizar un golpe medio a C con el puño izquierdo llevando el puño derecho sobre el hombo izquierdo",
      "Girando sobre el pie derecho formar una posicion para caminar a D realizar un bloqueo frontal medio con el antebrazo externo derecho (Realizar 30 y 31 como un movimiento continiado)",
      "Manteniendo la posicion para caminar realizar un golpe de puño izquierdo a D",
      "Realizar una patada frontal baja a D con el pie izquierdo manteniendo la posicion de las manos",
      "Bajar el pie izquierdo junto al derecho y luego con un pisoton desplazar el pie derecho a D formando una posicion para caminar realizando ungolpe alto a D con ambos puños verticales",
      "Llevar el pie izquierdo a una poscion preparatoria",
    ],
    times: [
      "0m02.678s",
      "0m04.378s",
      "0m05.882s",
      "0m06.653s",
      "0m08.519s",
      "0m10.461s",
      "0m11.909s",
      "0m12.884s",
      "0m14.877s",
      "0m16.450s",
      "0m18.053s",
      "0m19.849s",
      "0m21.770s",
      "0m23.451s",
      "0m25.122s",
      "0m26.056s",
      "0m29.400s",
      "0m30.825s",
      "0m33.150s",
      "0m34.882s",
      "0m36.102s",
      "0m37.760s",
      "0m39.355s",
      "0m41.502s",
      "0m42.857s",
      "0m44.718s",
      "0m46.479s",
      "0m48.017s",
      "0m49.770s",
      "0m50.983s",
      "0m51.863s",
      "0m52.953s",
      "0m54.850s",
      "0m58.688s",
    ],
  },
  yoosin: {
    name: "Yoo-Sin",
    dan: "III Dan",
    video: "8TOZVmWKJws",
    description:
      "Designado así por el General Kim Yoo Sin Comandante general durante la Dinastía Silla, que unió los 3 reinos separados de Corea.",
    belt: "Negro III DAN",
    diagram: "",
    qtyMovements: 68,
    junbi: "Moosa Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [
      "Dezplazar el pie izquierdo a B formando una posicion de jinete mirando a D, elevando los dos codos hacia los lados horizontalemnte",
      "Manteniendo la posicon de jinete, dar un golpe en angulo con el puño izquierdo a C, deslizando a A (Movimiento rapido)",
      "Manteniendo la posicion de jinete, dar un golpe en angulo con el puño derecho a C, deslizando a B (Movimiento rapido)",
      "Extendiendo las piernas realizar un bloqueo medio de agarre descendente con la palma derecha a D  (4 y 5 movimiento continuado)",
      "Formando una posicion de jinete dar un golpe de puño izquierdo a D (4 y 5 movimiento continuado)",
      "Extendiendo las piernas realizar un bloqueo medio de agarre descendente con la palma izquierda a D (6 y 7 Movimiento continuado)",
      "Formando una posicion de jinete dar un golpe de puño derecho a D (6 y 7 Movimiento continuado)",
      "Desplazar el pie izquierdo a BD (En diagonal) formando una posicion para caminar realizando un bloqueo lataral alto con antebrazo izquierdo",
      "Manteniendo la posicion para caminar realizar un bloqueo circular (Palmok Dollimyo Makgi) con el antebrazo interno derecho",
      "Formando una posicion de jinete mirando a AD realizar un bloqueo ascendente con la palma izquierda (Movimiento 10 y 11 conectado)",
      "Manteniendo la posicion de jinete dar un golpe de puño derecho a altura media a AD (Movimiento 10 y 11 conectado)",
      "Llevar el pie izquierdo junto al pie derecho, luego dezplazar el pie derecho a AD (Diagonal contraria) formando una  posicion para caminar realizando un bloqueo lateral alto con el antebrazo derecho",
      "Manteniendo la posicion para caminar realizar un bloqueo circular a AD con antebrazo izquierdo",
      "Formando una posicion de jinete realizar un bloqueo ascendente medio a BD con la palma derecha  (Movimiento 14 y 15 conectados)",
      "Manteniendo la posicion de jinete dar un golpe de puño izquierdo a alturamedia a BD (Movimiento 14 y 15 conectados)",
      "Formando una posicion de caminar a BC (Pierna izquierda adelante) realizar un bloqueo alto de agarre descendente con la palma derecha (Realizar movimientos 16, 17, 18 y 19 en un movimiento continuado)",
      "Volviendo a la poscion de jinete realizar un golpe de puño izquierdo a arltura media a BD  (Realizar movimientos 16, 17, 18 y 19 en un movimiento continuado)",
      "Formando una posicion para caminar a AD (Pierna derecha adelante) realizar un bloqueo alto de agarre descendente con la palma izquierda (Realizar movimientos 16, 17, 18 y 19 en un movimiento continuado)",
      "Volviendo a la posicion de jinete realizar un golpe de puño derecho a altura media a BD (Realizar movimientos 16, 17, 18 y 19 en un movimiento continuado)",
      "Dezplazar el pue derecho a C para formar una posicion para caminar mirando a D realizando un bloqueo bajo por presion con los puños en X (Realizar 20 y 21 de forma continua)",
      "Manteniendo la posicion de caminar realizar un bloqueo ascendente en forma de X con canto de mano  (Realizar 20 y 21 de forma continua)",
      "Manteniendo la posicion de caminar realize un golpe de puño medio a D con el puño derecho, llevando la palma izquierda sobre la articulacion del codo derecho",
      "Manteniendo la posicion de las manos del movimiento 22 realice una patada frontal baja a D con el pie derecho",
      "Bajar el pie derecho a D formando una posicion para caminar realizando un golpe de puño izquierdo a altura media",
      "Manteniendo la posicion de caminar realizar un bloqueo de presion con los puños en X (Realizar 25 y 26 de forma continua)",
      "Manteniendo la posicion de caminar realizar un bloqueo ascendente con canto de mano en X (Realizar 25 y 26 de forma continua)",
      "Manteniendo la posicion de caminar realizar un golpe a altura media a D con el puño izquierdo, llevando la palma de la mano derecha al codo izquierdo",
      "Manteniendo la posicion de las manos realizar una patada frontal baja a D con el pie izquierdo",
      "Bajar el pie izquierdo a D formando una posicion para caminar realizando un golpe de puño derecho",
      "Mueva el pie derecho a D formando una posicion en L y realizar un bloqueo a D con canto de mano derecha",
      "Mueva el pie izquierdo a D formando una poscion en L realizando un bloqueo a D con canto de mano izquierda",
      "Mueva el pie izquierdo a C (Hacia atras) formando una posicion en L realizando un bloqueo medio con canto de mano derecha a D",
      "Mueva el pie derecho a C (Hacia atras) formando una posicion en L  realizando un bloqueo medio con canto de mano izquierda a D",
      "Mueva el pie derecho a D formando una posicion para caminar realizando un bloqueo alto con antebrazo interno doble a D (Ejecute movimiento 34 y 35 rapidamente)",
      "Manteniendo la posicion para caminar realize un bloqueo bajo a D con el antebrazo externo izquierdo, manteniendo el brazo derecho (Ejecute movimiento 34 y 35 rapidamente)",
      "Mueva el pie izquierdo a D formando una posicion para caminar realizando un bloqueo alto con antebrazo interno doble izquierdo (Ejecute movimiento 36 y 37 rapidamente)",
      "Manteniendo la posicion para caminar realize un bloqueo bajo a D con el antebrazo externo derecho manteniendo el brazo izquierdo (Ejecute movimiento 36 y 37 rapidamente)",
      "Mueva el pie derecho a D realizando un golpe de puño medio derecho a D",
      "Dezplazar el pie izquierdo sobre la linea CD, girar sobre el pie izquierdo en sentido contrario a las agujas del reloj para formar una posicion en L (Mirando a C con la pierna izquierda adelante) realizando un bloqueo alto con el reverso de canto de mano izquierda",
      "Llevar el pie derecho junto al izquierdo para formar una posicion preparatoria de pies juntos tipo C, mirando a C",
      "Con un pisoton desplazar el pie derecho a CF formando una posicion para caminar realizando un golpe bajo en forma de gancho con ambos puños",
      "Llevar el pie derecho junto al izquierdo y con un pisoton dezplazar el pie izquierdo a CE realizando un golpe bajo en forma de gancho con ambos puños",
      "Llevar el pie izquierdo al derecho y dezplazar el pie derecho a F formando una posicion en L realizando un bloqueo medio a F con el antebrazo interno derecho",
      "Manteniendo la posicion en L realizar un golpe de puño izquiedo a altura media a F",
      "Llevar el pie izquierdo junto al derecho formando una posicion de pies juntos mirando a C, realizando un golpe en angulo con el puño derecho (Realizar lentamente)",
      "Desplazar elpie izquierdo a E formando una posicion en L realizando un bloqueo medio a E con antebrazo izquierdo",
      "Manteniendo la posicion en L Dar un golpe medio a E con el puño derecho",
      "Llevar el pie derecho junto al izquierdo formando una poscion de pies juntos (Mirando a C) realizando un golpe en angulo con el puño izquierdoo (Realizarlo lentamente)",
      "Dezplazar el pie izquierdo a E formando una posicion en L (Con peso repartido izquierda) dando un golpe a E en forma de U con ambos puños",
      "Llevar el pie izquierdo hacia el derecho, luego desplazar el pie derecho a E formando una posicion en L (Con peso repartido derecha) dando un golpe a E en forma de U con ambos puños",
      "Con un pisoton desplazar el pie derecho sobre la linea CD Para formar una posicion de jinete (Mirando a E) dando un golpe a E con el reverso del puño derecho",
      "Manteniendo la posicion de las manos realizar una patada de bloqueo hacia adentro y hacia D con el pie derecho, luego un bloqueo alto hacia afuera a AC con el antebrazo derecho, formando una poscion de jinete a E",
      "Manteniendo la posicion de las manos realizar una patada de bloqueo hacia adento y hacia C con el pie izquierdo, luego un bloqueo alto hacia EDcon el antebrazo derecho, formando una posicion de jinete a E",
      "Manteniendo la posicion de jinete realizar un golpe orizontal a C con el reverso del canto de la mano derecha",
      "Realizar una patada ascendente con el canto interno del pie izquierdo sobre la palma de la mano derecha (Realizar 55 y 56 de forma consecutiva)",
      "Sin bajar la pierna realizar una patada lateral a media a C, realizando un bloqueocon el antebrazo izquierdo (Realizar 55 y 56 de forma consecutiva)",
      "Bajar el pie izquierdo a C formando una posicion de jinete (Mirando a B) y dando un golpe orizontal con el reverso de la mano izquierda",
      "Realizar una patada ascendente con el canto interno del pie derecho sobre la palma de la mano izquierda (Realizar 58 y 59 de forma consecutiva)",
      "Sin bajar la pierna realizar una patada lateral a C, realizando un bloqueo con el antebrazo derecho",
      "Bajar el pie derecho a C formando una posicion de jinete (Mirando a A) realizando un bloqueo en forma de 9 derecho",
      "Manteniendo la posicion de jinete, realizar un bloqueo en forma de 9 izquierdo",
      "Desplazar el pie izquierdo a C girando en sentido de las agujas del reloj (De frente) formando una posicion de jinete a b realizando una defensa en 9 derecha",
      "Manteniendo la posicion de jinete realizar una defensa en 9 izquierda",
      "Moviendo el pie izquierdo formar una posicion vertical izquierda a D  realizar un puño descendente a D con el puño lateral derecho",
      "Dezplazar el pie derecho a A (Mirando a B) formando una posicion para caminar dando un golpe alto a B con los dos puños verticales",
      "Desplazar el pie derecho a B (Girando sobre el pie izquierdo y en sentido contrario a las agujas del reloj) formando una posicion para caminar dando un golpe alta a A con los dos puños verticales",
      "Llevar el pie derecho al pie izquierdo, desplazar el pie izquierdo a BD formando una posicion en L realizando un bloqueo en guardia medio con canto de manoi zquierda",
      "Llevar el pie izquierdo hacia el pie derecho, desplazar el pie derecho a AD formando una posicion en L realizando un bloqueo en guardia medio con canto de mano derecha",
      "Llevar el pie derecho a la posicion preparatoria",
    ],
    times: [
      "0m02.405s",
      "0m03.572s",
      "0m04.216s",
      "0m05.165s",
      "0m05.840s",
      "0m06.685s",
      "0m07.350s",
      "0m08.770s",
      "0m10.152s",
      "0m11.316s",
      "0m11.680s",
      "0m13.544s",
      "0m14.890s",
      "0m16.077s",
      "0m16.490s",
      "0m17.343s",
      "0m17.786s",
      "0m18.298s",
      "0m18.879s",
      "0m20.616s",
      "0m21.921s",
      "0m23.201s",
      "0m24.405s",
      "0m25.833s",
      "0m27.329s",
      "0m28.835s",
      "0m30.224s",
      "0m31.290s",
      "0m32.777s",
      "0m34.425s",
      "0m36.092s",
      "0m37.746s",
      "0m39.348s",
      "0m40.797s",
      "0m41.512s",
      "0m43.447s",
      "0m44.182s",
      "0m46.026s",
      "0m48.251s",
      "0m50.320s",
      "0m51.735s",
      "0m53.716s",
      "0m56.256s",
      "0m57.431s",
      "1m00s",
      "1m01.606s",
      "1m02.777s",
      "1m04.407s",
      "1m06.150s",
      "1m08.124s",
      "1m09.680s",
      "1m10.126s",
      "1m10.980s",
      "1m13.214s",
      "1m14.021s",
      "1m14.898s",
      "1m16.697s",
      "1m17.644s",
      "1m18.545s",
      "1m20.331s",
      "1m21.691s",
      "1m23.290s",
      "1m24.752s",
      "1m26.262s",
      "1m27.994s",
      "1m29.876s",
      "1m32.441s",
      "1m34.738s",
      "1m38.652s",
    ],
  },
  yongae: {
    name: "Yon-Gae",
    dan: "IV Dan",
    video: "8wX0JzYe8n0",
    description:
      "Proviene del nombre del famoso general de la dinastía de Koguryo Yon Gae Somoon. Los 49 movimientos se refieren a los dos últimas cifras del año 649 cuando obligó a la dnastía Tang a abandonar Corea, destruyendo casi a 300.000 de sus tropas en Ansi Sung.",
    belt: "Negro IV DAN",
    diagram: "Cruz",
    qtyMovements: 49,
    junbi: "Moosa Junbi Sogi",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  ulji: {
    name: "Ul-Ji",
    dan: "IV Dan",
    video: "ftELWqMPfZ4",
    description:
      "Proviene del nombre del general Ul-Ji Moon Dok, que defensió Corea con valentía contra la invasión de Tang y su ejército de casi un millón de soldados dirigidos por Yang Je en el año 612 A.C. Ul Ji utilizando técnicas de disuación y guerrilla pudo diezmar un alto porcentajo de la fuerza. En diagrama evoca su nombre. Los 42 movimientos representan la edad del autor cuando creó este tul.",
    belt: "Negro IV DAN",
    diagram: "",
    qtyMovements: 42,
    junbi: "",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [],
    times: [],
  },
  moonmoo: {
    name: "Moon-Moo",
    dan: "IV Dan",
    video: "vCwsyv0-Lno",
    description:
      "Hace honor al 30 rey de la dinastía Silla. Su cuerpo fue enterrado cerca de Dae Wang Am (roca del gran rey). Según su voluntad pusieron su cuerpo en el mar 'donde mi alma defenderá para siempre mi país contra los japoneses'. Se dice que Sok Gul Am (cueva) fue construido para guardar su tumba. El Sok Gul Am es un buen ejemplo de la cultura de la dinastía Silla. Los 61 movimientos simbolizan las dos últimos cifras del año 661, cuando Moon-Moo subió al trono.",
    belt: "Negro IV DAN",
    diagram: "Cruz",
    qtyMovements: 61,
    junbi: "Narani Junbi Sogi",
    start: "Pie izquierdo",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  sosan: {
    name: "So-San",
    dan: "V Dan",
    video: "8xFGvAzDMN0",
    description:
      "Es el seudónimo del célebre monje Choi Hyongh Ung (1520-1604) durante la dinastía Lee. Los 72 movimientos se refieren a su edad cuando organizó un cuerpo de monjes soldados con la ayuda de su alumno Sa Myung Dang. Esos monjes soldados ayudaron a expulsar los piratas japoneses que controlaban la mayor parte de la península en 1592.",
    belt: "Negro V DAN",
    diagram: "Cruz",
    qtyMovements: 72,
    junbi: "Narani Junbi Sogi A",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
  sejong: {
    name: "Se-Jong",
    dan: "V Dan",
    video: "4q-O1rxDyxI",
    description:
      "Proviene del nombre del más grande de los reyes coreanos, Se-Jong, quien inventó el alfabeto coreano en 1443, y quien era, también, un metereólogo famoso. El diagrama significa 'rey', mientras que los 24 movimientos se refieren a las 24 letras del alfabeto coreano.",
    belt: "Negro V DAN",
    diagram: "",
    qtyMovements: 24,
    junbi: "Moa Junbi Sogi B",
    start: "Pie izquierdo",
    finish: "Pie izquierdo",
    movements: [],
    times: [],
  },
  tongil: {
    name: "Tong-Il",
    dan: "VI Dan",
    video: "2M_8jaX_Okg",
    description:
      "Denota la resolución de reunificar Corea, dividida desde 1945. El diagrama simboliza la homogeneidad de raza.",
    belt: "Negro V DAN",
    diagram: "",
    qtyMovements: 56,
    junbi: "Moa Junbi Sogi C",
    start: "Pie derecho",
    finish: "Pie derecho",
    movements: [],
    times: [],
  },
};

let player;
/** Tul cuyo video y tiempos usan los movimientos (ej. "chonji") */
let activeTulKey = null;

/** Convierte formato YouTube (#t=0m01s o 0m01.234s) a segundos para la API */
function youtubeTimeToSeconds(t) {
  const m = String(t)
    .trim()
    .match(/^(\d+)m(\d+(?:\.\d+)?)s?$/i);
  if (!m) return 0;
  return parseInt(m[1], 10) * 60 + parseFloat(m[2]);
}

function onYouTubeIframeAPIReady() {
  player = new YT.Player("player", {
    height: "315",
    width: "560",
    videoId: tules.chonji.video,
    events: {
      onReady: function () {
        activeTulKey = "chonji";
        renderMovements("chonji");
      },
    },
  });
}

/**
 * Carga el video del tul y actualiza la lista de movimientos.
 * @param {string} key - clave en `tules` (ej. "chonji")
 */
function selectTul(key) {
  const tul = tules[key];
  if (!tul || !player || typeof player.loadVideoById !== "function") return;
  activeTulKey = key;
  player.loadVideoById({
    videoId: tul.video,
    startSeconds: 0,
  });
  renderMovements(key);
  document.getElementById("tul-name").textContent = tul.name;
  document.getElementById("tul-description").textContent = tul.description;
  document.getElementById("tul-belt").textContent = tul.belt;
  document.getElementById("tul-diagram").textContent = tul.diagram;
  document.getElementById("tul-qty-movements").textContent = tul.qtyMovements;
  document.getElementById("tul-junbi").textContent = tul.junbi;
  document.getElementById("tul-start").textContent = tul.start;
  document.getElementById("tul-finish").textContent = tul.finish;
}

/** Pinta los pasos del tul y enlaza cada uno al tiempo del video */
function renderMovements(key) {
  const tul = tules[key];
  const container = document.getElementById("tul-movements");
  if (!container || !tul || !tul.movements) return;
  container.innerHTML = "";
  tul.movements.forEach(function (text, i) {
    const row = document.createElement("div");
    row.className = "tul-movement-row";
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "tul-movement-btn";
    btn.textContent = i + 1 + ". " + text;
    btn.addEventListener("click", function () {
      goToMovement(i);
    });
    row.appendChild(btn);
    container.appendChild(row);
  });
}

/** Desplaza la vista hasta el reproductor de YouTube */
function scrollToVideo() {
  const el = document.getElementById("player");
  if (!el) return;
  el.scrollIntoView({ behavior: "smooth", block: "start" });
}

/** Salta al instante del movimiento `index` del tul activo */
function goToMovement(index) {
  if (!player || !activeTulKey) return;
  const tul = tules[activeTulKey];
  if (!tul.times || index < 0 || index >= tul.times.length) return;
  goTo(tul.times[index]);
  scrollToVideo();
}

/** Acepta segundos (número) o cadena tipo "0m01s" */
function goTo(time) {
  if (!player) return;
  const seconds = typeof time === "string" ? youtubeTimeToSeconds(time) : time;
  player.seekTo(seconds, true);
  player.pauseVideo();
}
